### ISSUE TITLE
[feat] Employer 핵심 로직 구현

### ISSUE THREAD

**Issue by 2zerozu** [SOPT-TEAM9-Carrot/Carrot-SERVER#11]
## 📌 Feature Issue

Employer 핵심 로직 구현

## 📝 To-do

- [x] Employer Domain 모델
- [x] Employer Service 인터페이스
- [x] Employer ServiceImpl 구현
