### ISSUE TITLE
[feat] User 핵심 로직 구성

### ISSUE THREAD

**Issue by 2zerozu** [SOPT-TEAM9-Carrot/Carrot-SERVER#7]
## 📌 Feature Issue

User 핵심 로직 구성

## 📝 To-do

 - [x] User Domain 모델
 - [x] User Service 인터페이스
 - [x] User ServiceImpl 구현
